spring.application.name=kitchensink-modernized

server.port=${SERVER_PORT:${PORT:8081}}
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/kitchensink}
spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true